In [1]:
# So now we will perform basic python functions on df using pandas

In [3]:
import pandas as pd

In [8]:
# Import the load_dataset function to fetch datasets from the Hugging Face Hub
from datasets import load_dataset

In [10]:
# This cell is responsible for loading a dataset and converting it into a pandas DataFrame.

# The 'load_dataset' function from the 'datasets' library is used to fetch the 'lukebarousse/data_jobs' dataset.
dataset = load_dataset('lukebarousse/data_jobs')

# After loading, we access the 'train' split of this dataset and convert it into a pandas DataFrame named 'df'.
# A pandas DataFrame is a tabular data structure that is widely used for data manipulation and analysis in Python.
df = dataset['train'].to_pandas()

In [18]:
#  lets see first row of the dataframe
df.head(1)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None

In [20]:
# similarily bottom rows
df.tail(1)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [21]:
# for detail of the whole dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [23]:
# Generates descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution.
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

In [26]:
# to get the speciic column
df.job_title_short

0         Senior Data Engineer
1                 Data Analyst
2                Data Engineer
3                Data Engineer
4                Data Engineer
                  ...
785736       Software Engineer
785737            Data Analyst
785738        Business Analyst
785739           Data Engineer
785740       Software Engineer
Name: job_title_short, Length: 785741, dtype: object

In [28]:
# or we can use
df['job_title_short']

0         Senior Data Engineer
1                 Data Analyst
2                Data Engineer
3                Data Engineer
4                Data Engineer
                  ...
785736       Software Engineer
785737            Data Analyst
785738        Business Analyst
785739           Data Engineer
785740       Software Engineer
Name: job_title_short, Length: 785741, dtype: object

In [36]:
# now we will apply the unique function to find unique values within the column
print(df['job_title_short'].unique())

# now i want to find the number of all unique values
df['job_title_short'].nunique()

['Senior Data Engineer' 'Data Analyst' 'Data Engineer' 'Business Analyst'
 'Data Scientist' 'Machine Learning Engineer' 'Senior Data Analyst'
 'Cloud Engineer' 'Senior Data Scientist' 'Software Engineer']

10

In [40]:
# suppose we want to look for two columns
df[['job_title_short','salary_year_avg']]

# i want to look for the job title which does not have nan
# We filter the dataframe where salary_year_avg is not null
df[df['salary_year_avg'].notna()][['job_title_short', 'salary_year_avg']]

       job_title_short  salary_year_avg
28      Data Scientist         109500.0
77       Data Engineer         140000.0
92       Data Engineer         120000.0
100     Data Scientist         228222.0
109       Data Analyst          89000.0
...                ...              ...
785624   Data Engineer         139216.0
785641   Data Engineer         150000.0
785648  Data Scientist         221875.0
785682  Data Scientist         157500.0
785692  Data Scientist         157500.0

[22003 rows x 2 columns]

In [46]:
# The .iloc function allows us to select a specific row by its integer index.
# Here we are retrieving the data for the 10th row (index 9).
df.iloc[9]

job_title_short                                             Data Scientist
job_title                                                Data Scientist II
job_location                                                      Anywhere
job_via                                                   via ZipRecruiter
job_schedule_type                                                Full-time
job_work_from_home                                                    True
search_location                                    New York, United States
job_posted_date                                        2023-04-23 13:02:57
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                           None
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                    Radwell International, LLC
job_skills               ['sql', 'python', 'r', 'mongodb', 'mongodb', '...
job_type_skills          {'analyst_tools': ['excel'], 'cloud': ['azure'...
Name: 9, dtype: object

In [51]:
# now lets provide a range for the iloc function
df.iloc[0:6]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."

In [55]:
# provide the range for the salary
display(df[df['salary_year_avg'] > 300000])

# suppose i want to find the total number with such condition
len(df[df['salary_year_avg'] > 300000])

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
679,Software Engineer,"Tech Lead Software Engineer, TikTok Data Access","San Jose, CA",via LinkedIn,Full-time,False,"Illinois, United States",2023-12-31 13:03:14,False,True,United States,year,317000.0,NaN,TikTok,"['java', 'go', 'c++', 'python', 'mongodb', 'mo...","{'databases': ['mongodb', 'mysql', 'redis'], '..."
4907,Senior Data Engineer,Senior Data Engineer - VP,"Pittsburgh, PA",via Ladders,Full-time,False,"Florida, United States",2023-05-01 13:10:38,False,True,United States,year,375000.0,NaN,The Bank of New York Mellon Corporation,"['power bi', 'dax']","{'analyst_tools': ['power bi', 'dax']}"
5628,Data Scientist,"Data Scientist Lead, Global Monetization Strat...","San Jose, CA",via LinkedIn,Full-time,False,"California, United States",2023-11-29 13:04:38,False,True,United States,year,361000.0,NaN,TikTok,"['r', 'python', 'sql']","{'programming': ['r', 'python', 'sql']}"
5862,Machine Learning Engineer,Principal Machine Learning Engineer,Anywhere,via LinkedIn,Full-time,True,Sudan,2023-11-24 14:22:22,False,False,Sudan,year,325000.0,NaN,Storm5,"['python', 'java', 'sql', 'aws', 'gcp', 'airfl...","{'cloud': ['aws', 'gcp'], 'libraries': ['airfl..."
13005,Data Scientist,Director of Data Science (Hybrid),"Dodgeville, WI",via Ladders,Full-time,False,"Illinois, United States",2023-03-03 13:04:55,False,False,United States,year,375000.0,NaN,Lands End,"['python', 'c', 'aws', 'pyspark', 'unity']","{'cloud': ['aws'], 'libraries': ['pyspark'], '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760507,Data Scientist,Head of Data Science,United States,via LinkedIn,Full-time,False,Sudan,2023-02-03 21:06:44,False,True,Sudan,year,351500.0,NaN,Demandbase,None,None
765640,Data Scientist,Director - Business Data Science,"New York, NY",via WJHL Jobs,Full-time,False,"New York, United States",2023-08-14 01:01:58,True,True,United States,year,314000.0,NaN,Figma,['go'],{'programming': ['go']}
772859,Data Scientist,"Staff Data Scientist, Financial Strategy","South San Francisco, CA",via Dice,Full-time,False,"California, United States",2023-12-12 01:02:36,False,True,United States,year,309152.0,NaN,Stripe,None,None
773874,Data Scientist,Data Science Manager,"San Francisco, CA",via Indeed,Full-time,False,"California, United States",2023-01-14 01:05:46,False,True,United States,year,308500.0,NaN,Grammarly,"['sql', 'python', 'r', 'scala']","{'programming': ['sql', 'python', 'r', 'scala']}"
777579,Data Analyst,Head of Data Analytics,"Austin, TX",via Ladders,Full-time,False,"Texas, United States",2023-10-23 05:02:56,False,True,United States,year,350000.0,NaN,Care.com,"['python', 'r', 'sql', 'snowflake', 'bigquery'...","{'analyst_tools': ['tableau', 'power bi', 'loo..."

149

In [58]:
# lets take it even further (We are looking for the Data Analyst Roles ONLY)
df[df['job_title_short'] == 'Data Analyst']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
12,Data Analyst,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False,France,2023-12-22 13:24:41,False,False,France,None,NaN,NaN,Engie,"['sql', 'php', 'excel', 'power bi', 'sap', 'ji...","{'analyst_tools': ['excel', 'power bi', 'sap']..."
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-10-16 13:36:54,False,False,Poland,None,NaN,NaN,Glovo,"['sql', 'python', 'r', 'redshift', 'pandas', '...","{'analyst_tools': ['excel', 'looker', 'tableau..."
31,Data Analyst,Stage - Data Analyst F/H,"Paris, France",via LinkedIn,Full-time and Internship,False,France,2023-10-19 13:59:31,False,False,France,None,NaN,NaN,GROUPE BON MARCHÉ : Le Bon Marché Rive Gauche ...,['sql'],{'programming': ['sql']}
34,Data Analyst,Data Analyst als Marketing Manager Automation ...,"Erlangen, Germany",via Central Illinois Proud Jobs,Full-time,False,Germany,2023-02-23 13:31:28,True,False,Germany,None,NaN,NaN,DEFACTO GmbH,['sap'],{'analyst_tools': ['sap']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Amul,None,None
785717,Data Analyst,Data & Analytics Architect (w/m/x),"Erfurt, Jerman",melalui LinkedIn,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,NTT DATA DACH,"['aws', 'azure']","{'cloud': ['aws', 'azure']}"
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."

In [60]:
# now we want to find the yearly salary with no nan values
df[df['salary_year_avg'].notna()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [61]:
# now if we want to find the rows in which job_title_short and salary_hour_avg are not nan
df[df['job_title_short'].notna() & df['salary_hour_avg'].notna()]
# with the result we can say that a total of 10662 items meets this condition

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
43,Senior Data Engineer,Sr SQL Database Engineer with Data Warehouse /...,None,via LinkedIn,Contractor,False,"Texas, United States",2023-09-13 13:06:55,True,False,United States,hour,NaN,97.500000,Phaxis,"['sql', 'sql server']","{'databases': ['sql server'], 'programming': [..."
51,Senior Data Engineer,Senior Data Engineer,Anywhere,via LinkedIn,Contractor,True,"Illinois, United States",2023-06-21 13:09:39,False,False,United States,hour,NaN,72.500000,Aditi Consulting,"['python', 'java', 'aws', 'databricks', 'spark']","{'cloud': ['aws', 'databricks'], 'libraries': ..."
253,Data Engineer,Data Engineer,Anywhere,via Upwork,Contractor and Temp work,True,Georgia,2023-11-26 13:54:45,True,False,United States,hour,NaN,88.000000,Upwork,"['sql', 'python', 'java', 'mysql', 'postgresql...","{'cloud': ['aws', 'gcp'], 'databases': ['mysql..."
294,Data Analyst,Business/Data Analyst,"Hartford, CT",via Dice,Contractor,False,"New York, United States",2023-07-03 13:00:08,False,False,United States,hour,NaN,52.500000,"Vector Consulting, Inc",None,None
340,Data Analyst,23-00059 BI Data Analysts + Media experience -...,California,via LinkedIn,Contractor,False,"California, United States",2023-02-28 13:01:46,True,False,United States,hour,NaN,67.500000,"iSpace, Inc.","['go', 'sql', 'aws', 'snowflake', 'tableau', '...","{'analyst_tools': ['tableau', 'looker', 'word'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784068,Data Engineer,"Manager, Data Engineering","New York, NY",via Snagajob,Full-time,False,Sudan,2023-08-12 06:37:26,False,True,Sudan,hour,NaN,54.420002,Vibrant Emotional Health,"['sql', 'python', 'r', 'snowflake', 'aws']","{'cloud': ['snowflake', 'aws'], 'programming':..."
784267,Senior Data Engineer,Senior Lead Data Engineer - Now Hiring,"Fredericksburg, VA",via Snagajob,Full-time and Part-time,False,"California, United States",2023-11-13 06:03:59,False,True,United States,hour,NaN,61.159996,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."
785111,Senior Data Engineer,"Health and Civil Data Engineer, Senior - Now H...","Bethesda, MD",via Snagajob,Full-time and Part-time,False,Georgia,2023-10-08 06:50:59,False,True,United States,hour,NaN,61.159996,Booz Allen Hamilton,"['python', 'sql', 'scala', 'java', 'shell', 'n...","{'cloud': ['aws', 'azure', 'databricks', 'reds..."
785476,Data Scientist,"Data Scientist, Lead","Washington, DC",via Snagajob,Full-time and Part-time,False,Georgia,2023-11-01 06:58:10,False,True,United States,hour,NaN,47.620003,Booz Allen Hamilton,"['databricks', 'azure', 'aws']","{'cloud': ['databricks', 'azure', 'aws']}"
785492,Data Scientist,Data Scientist,"Arlington, VA",via Snagajob,Full-time and Part-time,False,Georgia,2023-11-01 06:58:02,False,True,United States,hour,NaN,47.620003,Booz Allen Hamilton,"['python', 'r', 'pyspark']","{'libraries': ['pyspark'], 'programming': ['py..."

In [62]:
# now i wanto a boolean expression for the dataframe to know values are not missing
df.notna()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,False,False
1,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785737,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785738,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785739,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785740,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True