In [37]:
# now we will go to analysis part

In [38]:
import pandas as pd

In [39]:
from datasets import load_dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [40]:
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

In [41]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [43]:
# i want to create a new column named month name
df['month_name'] = df['job_posted_date'].dt.month_name()

In [44]:
# the number of jobs posted each month by month name in proper order (jan, feb, mar)
months_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
job_counts = df['month_name'].value_counts().reindex(months_order)
job_counts

month_name
January      91822
February     64578
March        64084
April        62919
May          52104
June         61572
July         63777
August       75162
September    62359
October      66611
November     64450
December     56303
Name: count, dtype: int64

In [45]:
# now i want to know the minimum value for salary_year_avg
df['salary_year_avg'].min()

15000.0

In [46]:
# now i want to find the location of this certain value
df['salary_year_avg'].idxmin()

665729

In [47]:
# to find the index 665729
df.loc[665729]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
month_name                                                        December
Name: 665729, dtype: object

In [48]:
# to know the location of the index
df.loc[665729]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
month_name                                                        December
Name: 665729, dtype: object

In [49]:
# we can also count individual values for certain column
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [53]:
# we can use group by function for certain data types
df.groupby('job_title_short')['salary_year_avg'].agg(['min','max','mean','median'])

                               min       max           mean    median
job_title_short
Business Analyst           16500.0  387460.0   91082.612833   85000.0
Cloud Engineer             42000.0  280000.0  111268.453846   90000.0
Data Analyst               25000.0  650000.0   93841.907854   90000.0
Data Engineer              15000.0  525000.0  130125.604250  125000.0
Data Scientist             27000.0  960000.0  135988.837171  127500.0
Machine Learning Engineer  30000.0  325000.0  126774.315972  106415.0
Senior Data Analyst        30000.0  425000.0  113911.363665  111175.0
Senior Data Engineer       35000.0  425000.0  145840.611624  147500.0
Senior Data Scientist      45000.0  890000.0  154206.292996  155500.0
Software Engineer          28000.0  375000.0  113393.760054   99150.0