In [2]:
# firstly we have to import libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

c:\Users\mrpra\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# now lets import dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
# now sort by date
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [11]:
# now we will create copy using the copy function
df_altered = df.copy()
df_altered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [12]:
# now we have to do replace Nan with '0'
df_altered.loc[:5,['salary_rate','salary_hour_avg','salary_year_avg']]

  salary_rate  salary_hour_avg  salary_year_avg
0        None              NaN              NaN
1        None              NaN              NaN
2        None              NaN              NaN
3        None              NaN              NaN
4        None              NaN              NaN
5        None              NaN              NaN

In [19]:
# ;lets get median salary first
median_salary = df_altered['salary_year_avg'].median()
median_salary

115000.0

In [27]:
# now we will fill all NaN values with median salary
df_altered['salary_year_avg'] = df_altered.loc[:,'salary_year_avg'].fillna(median_salary)

# now lets print it
df_altered.head(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,115000.0,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,115000.0,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,115000.0,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,115000.0,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,115000.0,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,115000.0,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,115000.0,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,None,115000.0,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,115000.0,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,115000.0,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [25]:
# now lets print both
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [28]:
# now we will try to get a random sample of data
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
184858,Data Engineer,"Data Engineer, Python, PostgreSQL, AWS COR5310",Anywhere,via Totaljobs,Full-time,True,United Kingdom,2023-10-02 15:34:08,True,False,United Kingdom,None,NaN,NaN,Corriculo Ltd,"['python', 'sql', 'postgresql', 'aws']","{'cloud': ['aws'], 'databases': ['postgresql']..."
159694,Senior Data Analyst,"Senior Analyst, Data Operations","Miami, FL",via BeBee,Full-time,False,"Florida, United States",2023-11-21 08:02:28,False,False,United States,None,NaN,NaN,Merieux NutriSciences,"['r', 'sql', 'python', 'oracle', 'tableau']","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
345637,Data Analyst,Principal Data Analyst,Australia,via Jobrapido.com,Full-time,False,Australia,2023-01-02 23:31:20,True,False,Australia,None,NaN,NaN,The State Of Queensland,"['python', 'sql', 'azure', 'power bi', 'dax', ...","{'analyst_tools': ['power bi', 'dax'], 'cloud'..."
507338,Business Analyst,Sales Analyst,India,via Adzuna,Full-time,False,India,2023-05-04 11:14:47,True,False,India,None,NaN,NaN,MTG LEARNING MEDIA PVT LTD,['excel'],{'analyst_tools': ['excel']}
99948,Data Analyst,HNP687 Ecommerce Reporting Analyst,Argentina,via Sercanto,Full-time,False,Argentina,2023-04-14 00:21:58,False,False,Argentina,None,NaN,NaN,The Ridge,"['r', 'sheets', 'excel', 'slack']","{'analyst_tools': ['sheets', 'excel'], 'progra..."

In [63]:
df_altered.sample(frac=0.01,replace=False,random_state=2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
631903,Data Analyst,Data Analyst Staff - Level 4,"Fort Worth, TX",via ZipRecruiter,Full-time,False,"Texas, United States",2023-07-28 12:01:23,True,False,United States,None,115000.0,NaN,Lockheed Martin,None,None
675347,Business Analyst,IT BUSINESS SYSTEMS ANALYST SENIOR,"Birmingham, AL",via KFOR Jobs,Full-time,False,Georgia,2023-03-26 10:39:19,False,True,United States,None,115000.0,NaN,First Horizon Bank,"['sql', 'c', 'sql server', 'db2', 'oracle', 'h...","{'cloud': ['oracle'], 'databases': ['sql serve..."
246258,Senior Data Analyst,"Senior Data Analyst, Business Intelligence (Mo...","Dublin, Ireland",via Hitmarker,Contractor,False,Ireland,2023-04-12 07:28:26,True,False,Ireland,None,115000.0,NaN,2K,"['sql', 'snowflake', 'aws', 'tableau', 'looker...","{'analyst_tools': ['tableau', 'looker', 'power..."
242366,Data Engineer,Data Engineer,"Portland, OR",via KHON2 Jobs,Full-time,False,Georgia,2023-06-08 07:47:42,False,True,United States,hour,115000.0,80.0,VanderHouwen,"['python', 'postgresql', 'aws', 'hadoop', 'lin...","{'cloud': ['aws'], 'databases': ['postgresql']..."
588047,Data Analyst,Data Analyst,France,via BeBee,Full-time,False,France,2023-01-05 09:40:31,True,False,France,None,115000.0,NaN,GAMIVO S.A.,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294952,Data Analyst,Business Intelligence And Data Analyst (m/f/d),"Stuttgart, Germany",via Your Basin Jobs,Full-time,False,Germany,2023-03-25 17:15:32,True,False,Germany,None,115000.0,NaN,Trelleborg Sealing Solutions Germany GmbH,None,None
263549,Machine Learning Engineer,Simulation & Machine Learning Engineer,Canada,via BeBee Canada,Full-time,False,Canada,2023-08-13 07:09:50,False,False,Canada,None,115000.0,NaN,Rumorcircle,"['python', 'jupyter', 'pandas', 'spark', 'tens...","{'libraries': ['jupyter', 'pandas', 'spark', '..."
613381,Data Engineer,Ingeniero de Datos - Trabajo Remoto,"Lima, Peru",via Melga,Full-time,False,Peru,2023-03-01 12:32:23,True,False,Peru,None,115000.0,NaN,BairesDev,None,None
221785,Business Analyst,Junior Business Analyst,"Tel Aviv-Yafo, Israel",via LinkedIn,Full-time,False,Israel,2023-01-16 23:15:51,False,False,Israel,None,115000.0,NaN,Sunday Security,None,None
427332,Data Engineer,Data Engineer,"Gurugram, Haryana, India",via Indeed,Full-time,False,India,2023-05-11 16:20:09,True,False,India,None,115000.0,NaN,IBM,['ibm cloud'],{'cloud': ['ibm cloud']}