# Apply method

In [22]:
# lets import libraries first
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Now Dataset 
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# sort by date
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  salary_year_inflated   22003 non-null   float64
dtypes: bool(3), datetime64[ns](1), float64(3), object(11)
memory usage: 92.2+ MB

In [31]:
# firstly we have to define a function in which project inflated salary will be 5% higher
def inflation(x):
    return x * 1.05

# now lets apply this function to the salary_year_avg column
df['salary_year_inflated'] = df['salary_year_avg'].apply(inflation)
df.head(10)

# # now we have remove NaN values
# df['salary_year_inflated'] = df['salary_year_inflated'].notna()
# df.head(10)

# lets delete NaN from salary_year_avg column
# df = df.dropna(subset=['salary_year_avg'])
# df

# now lets get the data frame for job title short, salary_year_avg and salary_year_inflated
df_inflated = df[['job_title_short','salary_year_avg','salary_year_inflated']]
df_inflated.reset_index()
df_inflated.set_index('job_title_short')

                      salary_year_avg  salary_year_inflated
job_title_short
Senior Data Engineer              NaN                   NaN
Data Analyst                      NaN                   NaN
Data Engineer                     NaN                   NaN
Data Engineer                     NaN                   NaN
Data Engineer                     NaN                   NaN
...                               ...                   ...
Software Engineer                 NaN                   NaN
Data Analyst                      NaN                   NaN
Business Analyst                  NaN                   NaN
Data Engineer                     NaN                   NaN
Software Engineer                 NaN                   NaN

[785741 rows x 2 columns]

In [33]:
# now we want only filled salary_year_avg columns
df_inflated = df_inflated.dropna(subset=['salary_year_avg'])
df_inflated.sample(10)

                  job_title_short  salary_year_avg  salary_year_inflated
547133              Data Engineer         156500.0             164325.00
151135       Senior Data Engineer         173500.0             182175.00
81055       Senior Data Scientist         154000.0             161700.00
668472             Data Scientist          90000.0              94500.00
435949               Data Analyst         138516.0             145441.80
287165              Data Engineer          97444.0             102316.20
547931      Senior Data Scientist         162500.0             170625.00
596794               Data Analyst         111175.0             116733.75
578468              Data Engineer         133000.0             139650.00
413932  Machine Learning Engineer         110000.0             115500.00

In [38]:
# now lets check for the format of job_skills
type(df['job_skills'][1])

str

In [46]:
# now to convert job_skills to a list we have to import ast
import ast

# now lets convert whole job_skills column to a list
type(ast.literal_eval(df['job_skills'][1]))

# now lets check for other columns
type(df['job_skills'][5])

str

In [ ]:
# we want whole column in list format
# handle NaN values by returning empty list instead of trying to parse them

df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if pd.notna(x) else []
)
df['job_skills'].head(10)

0                                                   []
1           [r, python, sql, nosql, power bi, tableau]
2    [python, sql, c#, azure, airflow, dax, docker,...
3    [python, c++, java, matlab, aws, tensorflow, k...
4    [bash, python, oracle, aws, ansible, puppet, j...
5                                   [python, sql, gcp]
6    [sql, python, java, sql server, gcp, bigquery,...
7    [sql, nosql, gcp, azure, aws, bigquery, databr...
8                        [excel, powerpoint, power bi]
9    [sql, python, r, mongodb, mongodb, sql server,...
Name: job_skills, dtype: object

In [53]:
# now lets check radndomly
type(df['job_skills'][516])

# everytime we are getting list

list